_target_: flavors.model_flavors.lightgbm_classifier.LightGBMClassifier
model:
  _target_: lightgbm.LGBMClassifier
  objective: binary
  is_unbalance: True
  extra_trees: True
  boosting_type: gbdt
  feature_fraction: 0.75
  feature_fraction_bynode: 0.95
  learning_rate: 0.020296
  max_bin: 32
  max_depth: 5
  min_data_in_bin: 835
  min_data_in_leaf: 505
  num_leaves: 130
  sigmoid: 2.4
  num_iterations: 3
  seed: 42