model:
  parameters:
    objective: binary
    is_unbalance: True
    extra_trees: False
    boosting_type: gbdt
    feature_fraction: 0.6
    feature_fraction_bynode: 0.95
    learning_rate: 0.034744
    max_bin: 107
    max_depth: 8
    min_data_in_bin: 885
    min_data_in_leaf: 595
    num_leaves: 475
    sigmoid: 8.3
    num_iterations: 290
  features:
    categorical:
      - cat_1
      - cat_2
      - cat_3
      - cat_4
      - cat_5
    numerical:
      - num_1
    target: my_target_column

pipeline_variables:
  gcp_project_options:
    dev: dev-case_3-project
    prod: prod-case_3-project

  options_table_features:
    dev: "case_3_dataset.features_table"
    prd: ${.dev}

  schedule: "0 0 * * *"