model:
  parameters:
    objective: binary
    is_unbalance: True
    extra_trees: False
    boosting_type: gbdt
    feature_fraction: 0.6
    feature_fraction_bynode: 0.95
    learning_rate: 0.034744
  features:
    categorical:
      - cat_1
      - cat_2
      - cat_3
      - cat_4
    numerical:
      - num_1
      - num_2
      - num_3
      - num_4
      - num_5
      - num_6
    target: my_target_column

pipeline_variables:
  gcp_project_options:
    dev: ???
    prod: ???

  options_table_features:
    dev: ???
    prd: ${.dev}

  schedule: ???